### ISSUE TITLE
Model returns a mask shape of (512,512,100) during testing

### ISSUE THREAD

**Issue by bahmed11** [ryanzhangfan/PA-Net#3]
When testing the model after training, the model returns a mask of shape (512,512,100) instead of (512,512,1). I believe this is because we add the fully connected layers and add its output to the output of the FCN. Should I replace the last layer just before the FC layers in "build_fpn_mask_graph":

	x = KL.TimeDistributed(KL.Activation('sigmoid'))(x)

with the layer:

	x = KL.TimeDistributed(KL.Conv2D(num_classes, (1, 1), strides=1, activation="sigmoid"),
						   name="mrcnn_mask")(x)

 to output a mask of shape (512,512,1) ?

**Comment by ryanzhangfan** [comment]
@bahmed11 Hi, the third dimension of the output represents the number of instances detected by the model. For more output format details, please see detect() in model.py. The model output a binary mask for each instance. If you want to get the final result (one mask for one image), you need to fuse the masks manually.

**Comment by bahmed11** [comment]
@ryanzhangfan Thank you for your reply. I have another question:

I trained the model and it converged at some point that is way lower in accuracy than the original Mask R-CNN model. Did you test this repo and got the same numbers as those published in the paper?

**Comment by ryanzhangfan** [comment]
@bahmed11 Hi, I haven't test my repo on benchmarks like coco or cityscapes yet. And it's on my todo list. By the way, did you compared the result with [Facebook version of maskrcnn](https://github.com/facebookresearch/Detectron) or [matterport version](https://github.com/matterport/Mask_RCNN)? As far as I know, facebook version can get much higher mAP on COCO dataset than matterport version(36.4 vs 29.x).

**Comment by bahmed11** [comment]
@ryanzhangfan Yes i am just done with the testing and all working now and i got better results than the original version on my own dataset
