### ISSUE TITLE
rpn anchors' scales

### ISSUE THREAD

**Issue by destinyzs** [ryanzhangfan/PA-Net#5]
In the appendix of original paper, it says `The RPN anchors span 7 scales, i.e., {8^2; 16^2; 32^2; 64^2; 128^2; 256^2; 512^2}, and 5 aspect ratios, i.e., {0:2; 0:5; 1; 2; 5}.`. I have some questions about it.
The FPN stage only has `N2, N3, N4, N5` 4 levels, so how these 7 scales distribute? Did it add extra levels of stage(`i.e., add 2 extra stage`) or use two scales in single stage`(i.e., use 8^2 and 16^2 in N2`)?

**Comment by ryanzhangfan** [comment]
@destinyzs I'm afraid I cannot answer your question with certainty. In my opinion, I prefer the latter one since it's how the anchor mechanism works in faster rcnn paper.

**Comment by destinyzs** [comment]
Thanks!
